[theme]
base = "dark"
primaryColor = "#B88746"
backgroundColor = "#151515"
secondaryBackgroundColor = "#202020"
textColor = "#F6F5F2"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true
