[theme]
base = "dark"
primaryColor = "#4F8FD8"
backgroundColor = "#E3E7EC"
secondaryBackgroundColor = "#F2F5F8"
textColor = "#2A4B70"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true
